### ISSUE TITLE
Error while loading this mod

### ISSUE THREAD

**Issue by zagliv** [Sewer56/CriFsHook.ReloadedII#1]
I was trying to launch Sonic Heroes in widescreen resolution. I followed this guide (modding essentials): https://www.pcgamingwiki.com/wiki/Sonic_Heroes#Mods

I assume that the problem is hidden exactly in this mod because I tried turning it off and launching the game with other mods enabled and game launched successfully (except for one thing, I don't know how to make my game run fullscreen. Borderless fullscreen windowed mode works kinda ok, but height is a tiny bit too big and that's causing 1% of the lower and upper half to go outside of the boundaries).

Here are my crash-log:

[01:17:44] [Reloaded] Create Loader | Time: 48ms
[01:17:44] [Reloaded] Create Loader Host (Async) | Time: 32ms
[01:17:44] [Reloaded] Loading Assembly Metadata for Inter Mod Communication, Determining Unload Support etc.: Complete 11ms
[01:17:44] [Reloaded] Prepared Mod: reloaded.sharedlib.hooks: Complete 1ms
[01:17:44] [Reloaded] Prepared Mod: criware.filesystem.hook: Complete 1ms
[01:17:44] [Reloaded] Prepared Mod: reloaded.sharedlib.csharp.prs: Complete 2ms
[01:17:44] [Reloaded] Prepared Mod: sonicheroes.utils.toner: Complete 2ms
[01:17:44] [Reloaded] Prepared Mod: sonicheroes.essentials.graphics: Complete 6ms
[01:17:44] [Reloaded] Prepare All Mods (Total): Complete 7ms
[01:17:44] [Reloaded] Initialized Mod: reloaded.sharedlib.hooks: Complete 0ms
[01:17:44] [Reloaded] Initialized Mod: reloaded.sharedlib.csharp.prs: Complete 0ms
[01:17:44] [Reloaded] Checking DRM, Hooking Process Exit (Async) | Time: 45ms
[01:17:44] [Reloaded] Initialized Mod: sonicheroes.utils.toner: Complete 43ms
[01:18:01] Failed to Load Reloaded-II.
Exception of type 'System.OutOfMemoryException' was thrown.
   at Reloaded.Memory.Buffers.MemoryBufferHelper.Run[T](Int32 retries, Func`1 function)
   at Reloaded.Memory.Buffers.MemoryBufferHelper.CreatePrivateMemoryBuffer(Int32 size, Int64 minimumAddress, Int64 maximumAddress, Int32 retryCount)
   at CriFsHook.ReloadedII.CriHook.CreateNewBuffer()
   at CriFsHook.ReloadedII.CriHook..ctor(IModLoader modLoader)
   at CriFsHook.ReloadedII.Program.Start(IModLoaderV1 loader)
   at Reloaded.Mod.Loader.Mods.Structs.ModInstance.Start(IModLoader loader)
   at Reloaded.Mod.Loader.Mods.PluginManager.StartMod(ModInstance instance)
   at Reloaded.Mod.Loader.Mods.PluginManager.ExecuteWithStopwatch[T](String message, Action`1 code, T parameter)
   at Reloaded.Mod.Loader.Mods.PluginManager.StartAllInstances(ModInstance[] instances)
   at Reloaded.Mod.Loader.Mods.PluginManager.ExecuteWithStopwatch[T](String message, Action`1 code, T parameter)
   at Reloaded.Mod.Loader.Mods.PluginManager.LoadMods(List`1 modPaths)
   at Reloaded.Mod.Loader.Loader.LoadModsWithDependencies(IEnumerable`1 modsToLoad, List`1 allMods)
   at Reloaded.Mod.Loader.Loader.LoadForAppConfig(IApplicationConfig applicationConfig)
   at Reloaded.Mod.Loader.Loader.LoadForCurrentProcess()
   at Reloaded.Mod.Loader.EntryPoint.LoadMods()
   at Reloaded.Mod.Loader.EntryPoint.ExecuteTimed(String text, Action action)
   at Reloaded.Mod.Loader.EntryPoint.SetupLoader()
A log is available at: C:\Users\Username\AppData\Roaming\Reloaded-Mod-Loader-II\Logs\2021-01-31 01.17.44 ~ Tsonic_win.txt
[01:18:53] [Reloaded] ExitProcess Hook: Log End

**Comment by Sewer56** [comment]
I updated the mod with newer library/dependency version.
It shouldn't fix your issue but can you update (it auto-updates in launcher) and run again.

You'll may come across the same error but I want to know just to make sure.

I know someone else has come across this kind of error a year ago; it was fixed though.
I've been a bit lazy (since I manage 20+ mods) to keep my Github versions up to date sometimes; as the latest versions are on the server from which Reloaded auto-updates from.

**Comment by zagliv** [comment]
![Untitled](https://user-images.githubusercontent.com/15791462/106507155-50b75000-64d3-11eb-8cac-3765262a5524.png)

Thanks for trying to help me with this problem. I got the new version. Still getting the same error:

[21:21:23] [Reloaded] Create Loader | Time: 47ms
[21:21:23] [Reloaded] Create Loader Host (Async) | Time: 27ms
[21:21:23] [Reloaded] Loading Assembly Metadata for Inter Mod Communication, Determining Unload Support etc.: Complete 11ms
[21:21:23] [Reloaded] Prepared Mod: reloaded.sharedlib.hooks: Complete 2ms
[21:21:23] [Reloaded] Prepared Mod: reloaded.sharedlib.csharp.prs: Complete 3ms
[21:21:23] [Reloaded] Prepared Mod: sonicheroes.utils.toner: Complete 3ms
[21:21:23] [Reloaded] Prepared Mod: criware.filesystem.hook: Complete 4ms
[21:21:23] [Reloaded] Prepared Mod: sonicheroes.essentials.graphics: Complete 7ms
[21:21:23] [Reloaded] Prepare All Mods (Total): Complete 7ms
[21:21:23] [Reloaded] Initialized Mod: reloaded.sharedlib.hooks: Complete 0ms
[21:21:23] [Reloaded] Initialized Mod: reloaded.sharedlib.csharp.prs: Complete 1ms
[21:21:23] [Reloaded] Checking DRM, Hooking Process Exit (Async) | Time: 46ms
[21:21:23] [Reloaded] Initialized Mod: sonicheroes.utils.toner: Complete 43ms
[21:21:40] Failed to Load Reloaded-II.
Exception of type 'System.OutOfMemoryException' was thrown.
   at Reloaded.Memory.Buffers.MemoryBufferHelper.Run[T](Int32 retries, Func`1 function)
   at Reloaded.Memory.Buffers.MemoryBufferHelper.CreatePrivateMemoryBuffer(Int32 size, Int64 minimumAddress, Int64 maximumAddress, Int32 retryCount)
   at CriFsHook.ReloadedII.CriHook.CreateNewBuffer()
   at CriFsHook.ReloadedII.CriHook..ctor(IModLoader modLoader)
   at CriFsHook.ReloadedII.Program.Start(IModLoaderV1 loader)
   at Reloaded.Mod.Loader.Mods.Structs.ModInstance.Start(IModLoader loader)
   at Reloaded.Mod.Loader.Mods.PluginManager.StartMod(ModInstance instance)
   at Reloaded.Mod.Loader.Mods.PluginManager.ExecuteWithStopwatch[T](String message, Action`1 code, T parameter)
   at Reloaded.Mod.Loader.Mods.PluginManager.StartAllInstances(ModInstance[] instances)
   at Reloaded.Mod.Loader.Mods.PluginManager.ExecuteWithStopwatch[T](String message, Action`1 code, T parameter)
   at Reloaded.Mod.Loader.Mods.PluginManager.LoadMods(List`1 modPaths)
   at Reloaded.Mod.Loader.Loader.LoadModsWithDependencies(IEnumerable`1 modsToLoad, List`1 allMods)
   at Reloaded.Mod.Loader.Loader.LoadForAppConfig(IApplicationConfig applicationConfig)
   at Reloaded.Mod.Loader.Loader.LoadForCurrentProcess()
   at Reloaded.Mod.Loader.EntryPoint.LoadMods()
   at Reloaded.Mod.Loader.EntryPoint.ExecuteTimed(String text, Action action)
   at Reloaded.Mod.Loader.EntryPoint.SetupLoader()
A log is available at: C:\Users\Username\AppData\Roaming\Reloaded-Mod-Loader-II\Logs\2021-02-01 21.21.23 ~ Tsonic_win.txt

**Comment by Sewer56** [comment]
Can you swing by the Reloaded Discord and ping me in there? Sounds like it's going to probably be a lot of trial and error.
